### ISSUE TITLE
Blocking sublime when no connection to perforce is available

### ISSUE THREAD

**Issue by pwntester** [daumiller/P4Gutter#1]
thanks for the cool plugin.

Im having a problem with it though, sublime gets completly blocked while trying to connect to the p4 server fi no connection is available. It remains blocked until the p4 command timesout. Can you please use a thread to run p4 commands so they dont block sublime?

Thanks,
A

**Comment by daumiller** [comment]
Thanks for the report! I'm working on this now. Unfortunately I don't think it's as easy as just throwing it in a thread. I don't wan't to pollute the system with tons of subprocesses waiting for connection timeouts if you go opening or saving multiple files. (Also, what would happen if the command did work, but took long enough to complete that you'd already closed the file, and we tried to reference a closed view?) I'm thinking about something where, if a diff takes longer than some configurable timeout it will prompt you to enter an 'offline' mode; and every X minutes in offline mode, prompt you to retry if it detects your network address has changed (staying silent until a Sublime restart otherwise). I'll also add in an 'enabled' flag to the config; so you can completely disable the plugin and go offline/off-network for an extended period of time without being continually nagged by P4Gutter.

Do you think waiting X seconds during the very first connection timeout, and being prompted every Y minutes to re-enable, _if_ your address has changed during that time, would be too disruptive a solution?

**Comment by pwntester** [comment]
Thanks for looking into it. In my case,  I only use p4 through a VPN server every now and then so for me having a switch to disable p4gutter works ok. In this case I will only enable it when connection is ready, so I wont care about the timeout.

Im thinking that a better solution to have to enable it manually can be to to ping the p4 server (P4PORT) and only in case its responding initiate the p4 commands. So only a ping needs to be sent on every file opened or saved.

**Comment by pwntester** [comment]
Hi, any news on this? what do you think about the ping idea?

**Comment by daumiller** [comment]
I made a new release earlier today with the "enabled" flag added to preferences (I believe Package Control will auto update this for you; if not, just check for version 1.3.1). I'll get something more useful going once I have some free time. I think pinging could work well, although some machines are configured to ignore ping requests. I may just do pinging; it sounds easier; but add it as an option, so we don't force everybody to rely on it. Thank you for your suggestions! I'll be sure to update this issue when I have something more complete implemented.

**Comment by pwntester** [comment]
Cool, thanks a lot!
